--THIS CODE IS NOT FUNCTIONAL BECAUSE OF THE SEG_MIN FIELD

DECLARE snapshot_date STRING DEFAULT '20250901';

EXECUTE IMMEDIATE FORMAT("""
    SELECT DISTINCT
        NAME,
        CASE_TYPE_CODE
    FROM `blm_seta_dqimp.blm_product_%s`
    WHERE 
        CASE_TYPE_CODE IN ('386000', '386200', '386210', '386300', '386310', '386400', '386403', '386501') 
        OR CASE_TYPE_CODE LIKE '00%%' OR CASE_TYPE_CODE LIKE '16%%' 
        OR CASE_TYPE_CODE LIKE '17%%' OR CASE_TYPE_CODE LIKE '18%%' 
        OR CASE_TYPE_CODE LIKE '20%%' OR CASE_TYPE_CODE LIKE '21%%' 
        OR CASE_TYPE_CODE LIKE '22%%' OR CASE_TYPE_CODE LIKE '23%%' 
        OR CASE_TYPE_CODE LIKE '24%%' OR CASE_TYPE_CODE LIKE '25%%' 
        OR CASE_TYPE_CODE LIKE '26%%' OR CASE_TYPE_CODE LIKE '27%%' 
        OR CASE_TYPE_CODE LIKE '40%%' OR CASE_TYPE_CODE LIKE '42%%' 
        OR CASE_TYPE_CODE LIKE '43%%' OR CASE_TYPE_CODE LIKE '50%%' 
        OR CASE_TYPE_CODE LIKE '54%%' OR CASE_TYPE_CODE LIKE '55%%' 
        OR CASE_TYPE_CODE LIKE '82%%' OR CASE_TYPE_CODE LIKE '83%%' 
        OR CASE_TYPE_CODE LIKE '85%%' 
            AND SEG_MIN IS NOT NULL
    ORDER BY NAME
""", snapshot_date);
